project_id = "epagtlrtzwdvferumowx"

[functions.generate-notes]
verify_jwt = true

[functions.explain-text]
verify_jwt = true

[functions.generate-study-tool]
verify_jwt = true

[functions.generate-fun-fact]
verify_jwt = true

[functions.generate-retention-quiz]
verify_jwt = true
